### ISSUE TITLE
i cant put to work

### ISSUE THREAD

**Issue by guilhermeduane** [landroo/MapsForgeServer#1]
Hello,  i follow the instructions but the server not load the tiles. Can you give me more detailed instructions?

**Comment by landroo** [comment]
I don't know.
Maybe something changed since last years int the file format.
But I can send you my working ones.
http://landroo.dynu.com/map.html
https://1drv.ms/u/s!ApdxzoDejecckek53wtDZBsXs4OUow

guilhermeduane <notifications@github.com> ezt írta (időpont: 2019. ápr.
29., H, 16:12):

**Comment by guilhermeduane** [comment]
I have the following problem:

Following its instructions I copy the root folder and maps to my directory, place the .map file in the maps folder and configure it in the .ini file.

In your instructions you say:

"Do not forget to replace the server url to your server url into the root / map.thml."

Which server is this? My map file is .map, but your configuration points to a .png file on the server in this mapsforge_tiles folder. (Http://192.168.0.46:8080/mapsforge_tiles/ {z} / {x} / {y}. png ') Could you tell me more about how to proceed? I do not have much experience with servers and maps.
Thank you

**Comment by landroo** [comment]
The map server contain the KtoHTTPD http server version 0.1 (based on
NanoHTTPD 1.14), Copyright 2001,2005-2010 Jarno Elonen). Its a simple
webserver.
The HttpServer.java service module check the requested tile cached then
sent it, if not the call maps forge (https://openmaps.eu/mapsforgedownload)
renderer and create it.
// http://yourserveraddress/osm_tiles/{z}/{x}/{y}.png
// http://192.168.0.46:8080/mapsforge_tiles/9/282/178.png
// /mapsforge_tiles/9/282/178.png
private boolean getTile(String uri) {
...
The NoteServer.java the main module. It's only load the ini files and set
the directory path. I something is inaccessible send an error message. At
the end it's start the web server.
File iniFile = new File("NoteServer.ini");
if(iniFile.exists())
{
Ini ini;
try
{
ini = new Ini("NoteServer.ini");
ns.port = Integer.parseInt(ini.get("HTTP", "port"));
ns.root = userHome + ini.get("HTTP", "root");
ns.tileRoot = ini.get("TileServer", "tileRoot");
ns.mapFiles = ini.get("TileServer", "mapFiles");
ns.renderXML = userHome + ini.get("TileServer", "renderXML");
Log.i(TAG, "Tile root: " + ns.tileRoot);
Log.i(TAG, "Map file: " + ns.mapFiles);
Log.i(TAG, "Render XML: " + ns.renderXML);
...
To display the map in the web browser I used leaflet.js.
https://leafletjs.com
L.tileLayer('http://192.168.0.46:8080/mapsforge_tiles/{z}/{x}/{y}.png',
{maxZoom:21}).addTo(map);
It's automatically request and display the tiles.

GoodLuck

guilhermeduane <notifications@github.com> ezt írta (időpont: 2019. máj. 3.,
P, 17:30):

**Comment by guilhermeduane** [comment]
It worked perfectly, thank you for your time.
